version: "3.8"

services:
  demo:
    image: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "8088:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    deploy:
      replicas: 5
      placement:
        preferences:
          - spread: node.hostname
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
