version: "3.8"

services:
  demo:
    image: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "8088:5000"
    deploy:
      replicas: 2
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
